apiVersion: v1
kind: Service
metadata:
  name: {{ template "padogridwithgrafana.name" . }}
  labels:
    app.kubernetes.io/name: {{ template "padogridwithgrafana.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    app.kubernetes.io/name: {{ template "padogridwithgrafana.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: {{ .Values.padogridWithGrafana.reachability.service.type }}
  ports:
    - name: {{ .Values.padogridWithGrafana.reachability.service.name }}
      port: {{ .Values.padogridWithGrafana.reachability.service.port }}
      targetPort: {{ .Values.padogridWithGrafana.instance.ports.web.name }}