apiVersion: v2
name: hazeltest
description: A Helm chart for deploying Hazeltest on Kubernetes

type: application

version: 1.1.0

appVersion: "0.5.2"

# Useful commands:
# helm upgrade --install hazeltest . --namespace=hazelcastimdg
# helm uninstall hazeltest --namespace=hazelcastimdg
