{{- if .Values.platform.deploy -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "hazelcastplatform.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ template "hazelcastplatform.name" . }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  hazelcast.yaml: |-
    hazelcast:
      cluster-name: {{ .Values.platform.config.clusterName }}
      properties:
        {{- toYaml .Values.platform.config.properties | nindent 8 }}
      management-center:
        {{- toYaml .Values.platform.config.managementCenter | nindent 8 }}
      metrics:
        {{- toYaml .Values.platform.config.metrics | nindent 8 }}
      jet:
        {{- toYaml .Values.platform.config.jet | nindent 8 }}
      {{- if .Values.platform.config.nativeMemory.enabled }}
      native-memory:
        {{- toYaml .Values.platform.config.nativeMemory | nindent 8 }}
      {{- end }}
      network:
        {{- toYaml .Values.platform.config.network | nindent 8 }}
      data-connection:
        {{- toYaml .Values.platform.config.dataConnection | nindent 8 }}
      map:
        {{- toYaml .Values.platform.config.map | nindent 8 }}
      queue:
        {{- toYaml .Values.platform.config.queue | nindent 8 }}
    {{- end -}}