{{- if .Values.platform.deploy -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "hazelcastplatform.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ template "hazelcastplatform.name" . }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  hazelcast.yaml: |-
{{ toYaml .Values.platform.config | indent 4 }}
{{- end -}}