apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "hazeltest.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ template "hazeltest.name" . }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  custom-config.yaml: |-
{{ toYaml .Values.config | indent 4 }}