{{ if or .Values.features.useDeletePodsServiceAccount .Values.features.useSccOnOpenShift -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
{{ end -}}