apiVersion: v1
kind: Service
metadata:
  name: {{ template "hazelcastimdg.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "hazelcastimdg.name" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ template "hazelcastimdg.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
  - name: hzport
    protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: hzmember

  
    