{
 "title": "Hazelcast",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "kubernetes_namespace",
    "label": "kubernetes_namespace",
    "query": {
     "query": "label_values(kubernetes_namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "System Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Max System CPU Load",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(com_hazelcast_Metrics_systemCpuLoad{kubernetes_namespace=\"$kubernetes_namespace\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage (Heap): Used, Free, Committed, Max",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(com_hazelcast_Metrics_usedHeap{kubernetes_namespace=\"$kubernetes_namespace\", prefix=\"memory\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(com_hazelcast_Metrics_freeHeap{kubernetes_namespace=\"$kubernetes_namespace\", prefix=\"memory\"})",
     "legendFormat": "free"
    },
    {
     "expr": "sum(com_hazelcast_Metrics_committedHeap{kubernetes_namespace=\"$kubernetes_namespace\", prefix=\"memory\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(com_hazelcast_Metrics_maxHeap{kubernetes_namespace=\"$kubernetes_namespace\", prefix=\"memory\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Garbage Collections (Major, Minor)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(rate(jvm_gc_collection_seconds_count{kubernetes_namespace=\"hazelcastplatform\", gc=~\".+Young Generation\"}[$__rate_interval]))",
     "legendFormat": "minor"
    },
    {
     "expr": "max(rate(jvm_gc_collection_seconds_count{kubernetes_namespace=\"hazelcastplatform\", gc=~\".+Old Generation\"}[$__rate_interval]))",
     "legendFormat": "major"
    }
   ]
  },
  {
   "title": "Memory Usage (Native): Used, Free, Committed, Max",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(com_hazelcast_Metrics_usedNative{kubernetes_namespace=\"$kubernetes_namespace\", prefix=\"memory\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(com_hazelcast_Metrics_freeNative{kubernetes_namespace=\"$kubernetes_namespace\", prefix=\"memory\"})",
     "legendFormat": "free"
    },
    {
     "expr": "sum(com_hazelcast_Metrics_committedNative{kubernetes_namespace=\"$kubernetes_namespace\", prefix=\"memory\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(com_hazelcast_Metrics_maxNative{kubernetes_namespace=\"$kubernetes_namespace\", prefix=\"memory\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Cluster Size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_size{kubernetes_namespace=\"$kubernetes_namespace\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Client Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_clientCount{kubernetes_namespace=\"$kubernetes_namespace\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Number Of Pending Invocations",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_pending{kubernetes_namespace=\"$kubernetes_namespace\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  { "title": "Per-Member System Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "System CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_systemCpuLoad{kubernetes_namespace=\"$kubernetes_namespace\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Free Memory (Heap)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_freeHeap{kubernetes_namespace=\"$kubernetes_namespace\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Free Memory (Native)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_freeNative{kubernetes_namespace=\"$kubernetes_namespace\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage (Heap): Used, Free, Max",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_usedHeap{kubernetes_namespace=\"$kubernetes_namespace\", prefix=\"memory\"}",
     "legendFormat": "{{pod_name}} used"
    },
    {
     "expr": "com_hazelcast_Metrics_freeHeap{kubernetes_namespace=\"$kubernetes_namespace\", prefix=\"memory\"}",
     "legendFormat": "{{pod_name}} free"
    },
    {
     "expr": "com_hazelcast_Metrics_committedHeap{kubernetes_namespace=\"$kubernetes_namespace\", prefix=\"memory\"}",
     "legendFormat": "{{pod_name}} committed"
    },
    {
     "expr": "com_hazelcast_Metrics_maxHeap{kubernetes_namespace=\"$kubernetes_namespace\", prefix=\"memory\"}",
     "legendFormat": "{{pod_name}} max"
    }
   ]
  },
  {
   "title": "Garbage Collections (Major, Minor)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 9, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_count{kubernetes_namespace=\"hazelcastplatform\", gc=~\".+Young Generation\"}[$__rate_interval])",
     "legendFormat": "{{pod_name}} minor"
    },
    {
     "expr": "rate(jvm_gc_collection_seconds_count{kubernetes_namespace=\"hazelcastplatform\", gc=~\".+Old Generation\"}[$__rate_interval])",
     "legendFormat": "{{pod_name}} major"
    }
   ]
  },
  {
   "title": "Memory Usage (Native): Used, Free, Committed, Max",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_usedNative{kubernetes_namespace=\"$kubernetes_namespace\", prefix=\"memory\"}",
     "legendFormat": "{{pod_name}} used"
    },
    {
     "expr": "com_hazelcast_Metrics_freeNative{kubernetes_namespace=\"$kubernetes_namespace\", prefix=\"memory\"}",
     "legendFormat": "{{pod_name}} free"
    },
    {
     "expr": "com_hazelcast_Metrics_committedNative{kubernetes_namespace=\"$kubernetes_namespace\", prefix=\"memory\"}",
     "legendFormat": "{{pod_name}} committed"
    },
    {
     "expr": "com_hazelcast_Metrics_maxNative{kubernetes_namespace=\"$kubernetes_namespace\", prefix=\"memory\"}",
     "legendFormat": "{{pod_name}} max"
    }
   ]
  },
  { "title": "Maps Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Map Entries (Total; Primary+Backup)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(sum by (tag0)(com_hazelcast_Metrics_ownedEntryCount{kubernetes_namespace=\"$kubernetes_namespace\"}))+sum(sum by (tag0)(com_hazelcast_Metrics_backupEntryCount{kubernetes_namespace=\"$kubernetes_namespace\"}))",
     "legendFormat": "number of map entries"
    }
   ]
  },
  {
   "title": "Map Entries (Primaries Per Map, Top 100)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 7, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (tag0)(topk(100, com_hazelcast_Metrics_ownedEntryCount{kubernetes_namespace=\"$kubernetes_namespace\", tag0!~\"\\\"name=__sql.*\", tag0!~\"\\\"name=__jet.*\"}))",
     "legendFormat": "{{tag0}}"
    }
   ]
  },
  {
   "title": "Map Entries (Backups Per Map, Top 100)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (tag0)(topk(100, com_hazelcast_Metrics_ownedEntryCount{kubernetes_namespace=\"$kubernetes_namespace\", tag0!~\"\\\"name=__sql.*\", tag0!~\"\\\"name=__jet.*\"}))",
     "legendFormat": "{{tag0}}"
    }
   ]
  },
  {
   "title": "Entry Memory Cost (Total; Primary+Backup)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(sum by (tag0)(com_hazelcast_Metrics_ownedEntryMemoryCost{kubernetes_namespace=\"$kubernetes_namespace\"}))+sum(sum by (tag0)(com_hazelcast_Metrics_backupEntryMemoryCost{kubernetes_namespace=\"$kubernetes_namespace\"}))",
     "legendFormat": "memory cost"
    }
   ]
  },
  {
   "title": "Entry Memory Cost (Primaries, Per Map, Top 100)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 7, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (tag0)(topk(100, com_hazelcast_Metrics_ownedEntryMemoryCost{kubernetes_namespace=\"$kubernetes_namespace\", tag0!~\"\\\"name=__sql.*\", tag0!~\"\\\"name=__jet.*\"}))",
     "legendFormat": "{{tag0}}"
    }
   ]
  },
  {
   "title": "Entry Memory Cost (Backups, Per Map, Top 100)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (tag0)(topk(100, com_hazelcast_Metrics_backupEntryMemoryCost{kubernetes_namespace=\"$kubernetes_namespace\", tag0!~\"\\\"name=__sql.*\", tag0!~\"\\\"name=__jet.*\"}))",
     "legendFormat": "{{tag0}}"
    }
   ]
  },
  {
   "title": "Queries",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (tag0)(rate(com_hazelcast_Metrics_queryCount{kubernetes_namespace=\"$kubernetes_namespace\", tag0!~\"\\\"name=__sql.*\", tag0!~\"\\\"name=__jet.*\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Locked Entries",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (tag0)(rate(com_hazelcast_Metrics_lockedEntryCount{kubernetes_namespace=\"$kubernetes_namespace\", tag0!~\"\\\"name=__sql.*\", tag0!~\"\\\"name=__jet.*\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Expirations",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (tag0)(rate(com_hazelcast_Metrics_expirationCount{kubernetes_namespace=\"$kubernetes_namespace\", tag0!~\"\\\"name=__sql.*\", tag0!~\"\\\"name=__jet.*\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Evictions",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (tag0)(rate(com_hazelcast_Metrics_evictionCount{kubernetes_namespace=\"$kubernetes_namespace\", tag0!~\"\\\"name=__sql.*\", tag0!~\"\\\"name=__jet.*\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Map Set Count Across All Maps",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(sum by (tag0)(rate(com_hazelcast_Metrics_setCount{kubernetes_namespace=\"$kubernetes_namespace\", tag0!~\"\\\"name=__sql.*\", tag0!~\"\\\"name=__jet.*\"}[$__rate_interval])))",
     "legendFormat": "set count"
    }
   ]
  },
  {
   "title": "Map Put Count Across All Maps",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(sum by (tag0)(rate(com_hazelcast_Metrics_putCount{kubernetes_namespace=\"$kubernetes_namespace\", tag0!~\"\\\"name=__sql.*\", tag0!~\"\\\"name=__jet.*\"}[$__rate_interval])))",
     "legendFormat": "put count"
    }
   ]
  },
  {
   "title": "Map Get Count Across All Maps",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(sum by (tag0)(rate(com_hazelcast_Metrics_getCount{kubernetes_namespace=\"$kubernetes_namespace\", tag0!~\"\\\"name=__sql.*\", tag0!~\"\\\"name=__jet.*\"}[$__rate_interval])))",
     "legendFormat": "get count"
    }
   ]
  },
  {
   "title": "Map Remove Count Across All Maps",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(sum by (tag0)(rate(com_hazelcast_Metrics_removeCount{kubernetes_namespace=\"$kubernetes_namespace\", tag0!~\"\\\"name=__sql.*\", tag0!~\"\\\"name=__jet.*\"}[$__rate_interval])))",
     "legendFormat": "remove count"
    }
   ]
  },
  { "title": "Per-Map Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Map Set Count By Map, Top 100",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (tag0)(topk(100, rate(com_hazelcast_Metrics_setCount{kubernetes_namespace=\"$kubernetes_namespace\", tag0!~\"\\\"name=__sql.*\", tag0!~\"\\\"name=__jet.*\"}[$__rate_interval])))",
     "legendFormat": "{{ tag0 }}"
    }
   ]
  },
  {
   "title": "Map Put Count By Map, Top 100",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (tag0)(topk(100, rate(com_hazelcast_Metrics_putCount{kubernetes_namespace=\"$kubernetes_namespace\", tag0!~\"\\\"name=__sql.*\", tag0!~\"\\\"name=__jet.*\"}[$__rate_interval])))",
     "legendFormat": "{{ tag0 }}"
    }
   ]
  },
  {
   "title": "Map Get Count By Map, Top 100",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (tag0)(topk(100, rate(com_hazelcast_Metrics_getCount{kubernetes_namespace=\"$kubernetes_namespace\", tag0!~\"\\\"name=__sql.*\", tag0!~\"\\\"name=__jet.*\"}[$__rate_interval])))",
     "legendFormat": "{{ tag0 }}"
    }
   ]
  },
  {
   "title": "Map Remove Count By Map, Top 100",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (tag0)(topk(100, rate(com_hazelcast_Metrics_removeCount{kubernetes_namespace=\"$kubernetes_namespace\", tag0!~\"\\\"name=__sql.*\", tag0!~\"\\\"name=__jet.*\"}[$__rate_interval])))",
     "legendFormat": "{{ tag0 }}"
    }
   ]
  },
  {
   "title": "Average Set Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (tag0)(rate(com_hazelcast_Metrics_totalSetLatency{kubernetes_namespace=\"$kubernetes_namespace\", tag0!~\"\\\"name=__sql.*\", tag0!~\"\\\"name=__jet.*\"}[$__rate_interval]) / on(tag0, pod_name) rate(com_hazelcast_Metrics_setCount{kubernetes_namespace=\"$kubernetes_namespace\", tag0!~\"\\\"name=__sql.*\", tag0!~\"\\\"name=__jet.*\"}[$__rate_interval]))",
     "legendFormat": "{{ tag0 }}"
    }
   ]
  },
  {
   "title": "Average Put Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (tag0)(rate(com_hazelcast_Metrics_totalPutLatency{kubernetes_namespace=\"$kubernetes_namespace\", tag0!~\"\\\"name=__sql.*\", tag0!~\"\\\"name=__jet.*\"}[$__rate_interval]) / on(tag0, pod_name) rate(com_hazelcast_Metrics_PutCount{kubernetes_namespace=\"$kubernetes_namespace\", tag0!~\"\\\"name=__sql.*\", tag0!~\"\\\"name=__jet.*\"}[$__rate_interval]))",
     "legendFormat": "{{ tag0 }}"
    }
   ]
  },
  {
   "title": "Average Get Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (tag0)(rate(com_hazelcast_Metrics_totalGetLatency{kubernetes_namespace=\"$kubernetes_namespace\", tag0!~\"\\\"name=__sql.*\", tag0!~\"\\\"name=__jet.*\"}[$__rate_interval]) / on(tag0, pod_name) rate(com_hazelcast_Metrics_getCount{kubernetes_namespace=\"$kubernetes_namespace\", tag0!~\"\\\"name=__sql.*\", tag0!~\"\\\"name=__jet.*\"}[$__rate_interval]))",
     "legendFormat": "{{ tag0 }}"
    }
   ]
  },
  {
   "title": "Average Remove Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (tag0)(rate(com_hazelcast_Metrics_totalRemoveLatency{kubernetes_namespace=\"$kubernetes_namespace\", tag0!~\"\\\"name=__sql.*\", tag0!~\"\\\"name=__jet.*\"}[$__rate_interval]) / on(tag0, pod_name) rate(com_hazelcast_Metrics_removeCount{kubernetes_namespace=\"$kubernetes_namespace\", tag0!~\"\\\"name=__sql.*\", tag0!~\"\\\"name=__jet.*\"}[$__rate_interval]))",
     "legendFormat": "{{ tag0 }}"
    }
   ]
  },
  { "title": "Queues Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "Total Owned Items",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(sum by (tag0)(com_hazelcast_Metrics_ownedItemCount{kubernetes_namespace=\"$kubernetes_namespace\", prefix=\"queue\"}))",
     "legendFormat": "number of owned items"
    }
   ]
  }
 ]
}