{
 "title": "System Overview (New)",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "kubernetes_namespace",
    "label": "kubernetes_namespace",
    "query": {
     "query": "label_values(kubernetes_namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster CPU Load (Snapshot)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(com_hazelcast_Metrics_systemCpuLoad{kubernetes_namespace=\"$kubernetes_namespace\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Cluster Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_size{kubernetes_namespace=\"$kubernetes_namespace\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Client Count (Total)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(com_hazelcast_Metrics_clientCount{kubernetes_namespace=\"$kubernetes_namespace\"})",
     "legendFormat": "cluster-wide client count"
    }
   ]
  },
  {
   "title": "Client Count (By Member)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_clientCount{kubernetes_namespace=\"$kubernetes_namespace\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Number Of Pending Invocations",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_pending{kubernetes_namespace=\"$kubernetes_namespace\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Garbage Collections",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(rate(jvm_gc_collection_seconds_count{kubernetes_namespace=\"hazelcastplatform\", gc=~\".+Young Generation\"}[$__rate_interval]))",
     "legendFormat": "minor"
    },
    {
     "expr": "max(rate(jvm_gc_collection_seconds_count{kubernetes_namespace=\"hazelcastplatform\", gc=~\".+Old Generation\"}[$__rate_interval]))",
     "legendFormat": "major"
    }
   ]
  },
  {
   "title": "Memory Usage (Native): Used, Free, Committed, Max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(com_hazelcast_Metrics_usedNative{kubernetes_namespace=\"$kubernetes_namespace\", prefix=\"memory\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(com_hazelcast_Metrics_freeNative{kubernetes_namespace=\"$kubernetes_namespace\", prefix=\"memory\"})",
     "legendFormat": "free"
    },
    {
     "expr": "sum(com_hazelcast_Metrics_committedNative{kubernetes_namespace=\"$kubernetes_namespace\", prefix=\"memory\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(com_hazelcast_Metrics_maxNative{kubernetes_namespace=\"$kubernetes_namespace\", prefix=\"memory\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Memory Usage (Heap): Used, Free, Committed, Max (Snapshot)",
   "type": "barchart",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(com_hazelcast_Metrics_usedHeap{kubernetes_namespace=\"$kubernetes_namespace\", prefix=\"memory\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(com_hazelcast_Metrics_freeHeap{kubernetes_namespace=\"$kubernetes_namespace\", prefix=\"memory\"})",
     "legendFormat": "free"
    }
   ]
  },
  {
   "title": "Memory Usage (Heap): Used, Free, Committed, Max",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(com_hazelcast_Metrics_usedHeap{kubernetes_namespace=\"$kubernetes_namespace\", prefix=\"memory\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(com_hazelcast_Metrics_freeHeap{kubernetes_namespace=\"$kubernetes_namespace\", prefix=\"memory\"})",
     "legendFormat": "free"
    },
    {
     "expr": "sum(com_hazelcast_Metrics_committedHeap{kubernetes_namespace=\"$kubernetes_namespace\", prefix=\"memory\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(com_hazelcast_Metrics_maxHeap{kubernetes_namespace=\"$kubernetes_namespace\", prefix=\"memory\"})",
     "legendFormat": "max"
    }
   ]
  },
  { "title": "Per-Member Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_systemCpuLoad{kubernetes_namespace=\"$kubernetes_namespace\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Free Memory (Heap)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_freeHeap{kubernetes_namespace=\"$kubernetes_namespace\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Free Memory (Native)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_freeNative{kubernetes_namespace=\"$kubernetes_namespace\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage (Heap): Used, Free, Committed, Max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_usedHeap{kubernetes_namespace=\"$kubernetes_namespace\", prefix=\"memory\"}",
     "legendFormat": "{{ pod_name }} used"
    },
    {
     "expr": "com_hazelcast_Metrics_freeHeap{kubernetes_namespace=\"$kubernetes_namespace\", prefix=\"memory\"}",
     "legendFormat": "{{ pod_name }} free"
    },
    {
     "expr": "com_hazelcast_Metrics_committedHeap{kubernetes_namespace=\"$kubernetes_namespace\", prefix=\"memory\"}",
     "legendFormat": "{{ pod_name }} committed"
    },
    {
     "expr": "com_hazelcast_Metrics_maxHeap{kubernetes_namespace=\"$kubernetes_namespace\", prefix=\"memory\"}",
     "legendFormat": "{{ pod_name }} max"
    }
   ]
  },
  {
   "title": "Garbage Collections",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_count{kubernetes_namespace=\"hazelcastplatform\", gc=~\".+Young Generation\"}[$__rate_interval])",
     "legendFormat": "{{ pod_name }} minor"
    },
    {
     "expr": "rate(jvm_gc_collection_seconds_count{kubernetes_namespace=\"hazelcastplatform\", gc=~\".+Old Generation\"}[$__rate_interval])",
     "legendFormat": " {{ pod_name }} major"
    }
   ]
  },
  {
   "title": "Memory Usage (Native): Used, Free, Committed, Max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_usedNative{kubernetes_namespace=\"$kubernetes_namespace\", prefix=\"memory\"}",
     "legendFormat": "{{ pod_name }} used"
    },
    {
     "expr": "com_hazelcast_Metrics_freeNative{kubernetes_namespace=\"$kubernetes_namespace\", prefix=\"memory\"}",
     "legendFormat": "{{ pod_name }} free"
    },
    {
     "expr": "com_hazelcast_Metrics_committedNative{kubernetes_namespace=\"$kubernetes_namespace\", prefix=\"memory\"}",
     "legendFormat": "{{ pod_name }} committed"
    },
    {
     "expr": "com_hazelcast_Metrics_maxNative{kubernetes_namespace=\"$kubernetes_namespace\", prefix=\"memory\"}",
     "legendFormat": "{{ pod_name }} max"
    }
   ]
  },
  {
   "title": "Virtual Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{kubernetes_namespace=\"$kubernetes_namespace\"}",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  }
 ]
}