{
 "title": "Queues",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "kubernetes_namespace",
    "label": "kubernetes_namespace",
    "query": {
     "query": "label_values(kubernetes_namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number Of Owned Items By Queue (Snapshot)",
   "type": "barchart",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (tag0)(topk(100, com_hazelcast_Metrics_ownedItemCount{kubernetes_namespace=\"$kubernetes_namespace\", prefix=\"queue\"}))",
     "legendFormat": "{{tag0}}"
    }
   ]
  },
  {
   "title": "Owned Items (Per Queue, Top 100)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (tag0)(topk(100, com_hazelcast_Metrics_ownedItemCount{kubernetes_namespace=\"$kubernetes_namespace\", prefix=\"queue\"}))",
     "legendFormat": "{{tag0}}"
    }
   ]
  },
  {
   "title": "Backup Items (Per Queue, Top 100)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (tag0)(topk(100, com_hazelcast_Metrics_backupItemCount{kubernetes_namespace=\"$kubernetes_namespace\", prefix=\"queue\"}))",
     "legendFormat": "{{tag0}}"
    }
   ]
  },
  {
   "title": "Owned Items (Total; Primary+Backup)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(sum by (tag0)(com_hazelcast_Metrics_ownedItemCount{kubernetes_namespace=\"$kubernetes_namespace\", prefix=\"queue\"}))+sum(sum by (tag0)(com_hazelcast_Metrics_backupItemCount{kubernetes_namespace=\"$kubernetes_namespace\", prefix=\"queue\"}))",
     "legendFormat": "number of owned items"
    }
   ]
  },
  {
   "title": "Owned Items (Per Member)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (pod_name)(com_hazelcast_Metrics_ownedItemCount{kubernetes_namespace=\"$kubernetes_namespace\", prefix=\"queue\"})",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Backup Items (Per Member)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (pod_name)(com_hazelcast_Metrics_backupItemCount{kubernetes_namespace=\"$kubernetes_namespace\", prefix=\"queue\"})",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Average Age Of Items By Queue",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (tag0)(com_hazelcast_Metrics_averageAge{kubernetes_namespace=\"$kubernetes_namespace\"})",
     "legendFormat": "{{tag0}}"
    }
   ]
  },
  {
   "title": "Average Age Of Items By Member",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (pod_name)(com_hazelcast_Metrics_averageAge{kubernetes_namespace=\"$kubernetes_namespace\"})",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Events By Queue Per Second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (tag0)(rate(com_hazelcast_Metrics_numberOfEvents{kubernetes_namespace=\"$kubernetes_namespace\", prefix=\"queue\"}[$__rate_interval]))",
     "legendFormat": "{{tag0}}"
    }
   ]
  },
  {
   "title": "Operation Statistics: Offer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Number Of Offers",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(sum by (tag0)(com_hazelcast_Metrics_numberOfOffers{kubernetes_namespace=\"$kubernetes_namespace\", prefix=\"queue\"}))",
       "legendFormat": "number of offers"
      }
     ]
    },
    {
     "title": "Number Of Offers By Queue",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 9, "x": 6, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (tag0)(com_hazelcast_Metrics_numberOfOffers{kubernetes_namespace=\"$kubernetes_namespace\", prefix=\"queue\"})",
       "legendFormat": "{{tag0}}"
      }
     ]
    },
    {
     "title": "Number Of Rejected Offers By Queue",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 9, "x": 15, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (tag0)(com_hazelcast_Metrics_numberOfRejectedOffers{kubernetes_namespace=\"$kubernetes_namespace\", prefix=\"queue\"})",
       "legendFormat": "{{tag0}}"
      }
     ]
    },
    {
     "title": "Total Number Of Offers Per Second",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(sum by (tag0)(rate(com_hazelcast_Metrics_numberOfOffers{kubernetes_namespace=\"$kubernetes_namespace\", prefix=\"queue\"}[$__rate_interval])))",
       "legendFormat": "number of offers/sec"
      }
     ]
    },
    {
     "title": "Number Of Offers By Queue Per Second",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 9, "x": 6, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (tag0)(rate(com_hazelcast_Metrics_numberOfOffers{kubernetes_namespace=\"$kubernetes_namespace\", prefix=\"queue\"}[$__rate_interval]))",
       "legendFormat": "{{tag0}}"
      }
     ]
    },
    {
     "title": "Number Of Rejected Offers By Queue Per Second",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 9, "x": 15, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (tag0)(rate(com_hazelcast_Metrics_numberOfRejectedOffers{kubernetes_namespace=\"$kubernetes_namespace\", prefix=\"queue\"}[$__rate_interval]))",
       "legendFormat": "{{tag0}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Operation Statistics: Poll",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Number Of Polls",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(sum by (tag0)(com_hazelcast_Metrics_numberOfPolls{kubernetes_namespace=\"$kubernetes_namespace\", prefix=\"queue\"}))",
       "legendFormat": "number of offers"
      }
     ]
    },
    {
     "title": "Number Of Polls By Queue",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 9, "x": 6, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (tag0)(com_hazelcast_Metrics_numberOfPolls{kubernetes_namespace=\"$kubernetes_namespace\", prefix=\"queue\"})",
       "legendFormat": "{{tag0}}"
      }
     ]
    },
    {
     "title": "Number Of Empty Polls By Queue",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 9, "x": 15, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (tag0)(com_hazelcast_Metrics_numberOfEmptyPolls{kubernetes_namespace=\"$kubernetes_namespace\", prefix=\"queue\"})",
       "legendFormat": "{{tag0}}"
      }
     ]
    },
    {
     "title": "Total Number Of Polls Per Second",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(sum by (tag0)(rate(com_hazelcast_Metrics_numberOfPolls{kubernetes_namespace=\"$kubernetes_namespace\", prefix=\"queue\"}[$__rate_interval])))",
       "legendFormat": "number of offers/sec"
      }
     ]
    },
    {
     "title": "Number Of Polls By Queue Per Second",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 9, "x": 6, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (tag0)(rate(com_hazelcast_Metrics_numberOfPolls{kubernetes_namespace=\"$kubernetes_namespace\", prefix=\"queue\"}[$__rate_interval]))",
       "legendFormat": "{{tag0}}"
      }
     ]
    },
    {
     "title": "Number Of Empty Polls By Queue Per Second",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 9, "x": 15, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (tag0)(rate(com_hazelcast_Metrics_numberOfEmptyPolls{kubernetes_namespace=\"$kubernetes_namespace\", prefix=\"queue\"}[$__rate_interval]))",
       "legendFormat": "{{tag0}}"
      }
     ]
    }
   ]
  }
 ]
}