apiVersion: v2
name: padogridwithgrafana
description: A chart for deploying an image that launches a Grafana instance with dashboards from PadoGrid for monitoring one or more Hazelcast clusters.

type: application

version: 1.1.0

appVersion: "0.9.32"
