service:
  type: LoadBalancer
  port: 5701

cluster:
  logging:
    level: INFO
  members:
    image: hazelcast/hazelcast:5.1.1
    count: 1
    ports:
      member: 5701
      metrics: 8080
    gracefulShutDown:
      maxWaitSeconds: 60
    resources:
      requests:
        cpu: "1"
        memory: "3G"
      limits:
        cpu: "1"
        memory: "3G"
    liveness:
      initialDelaySeconds: 15
      periodSeconds: 10
    readiness:
      initialDelaySeconds: 30
      periodSeconds: 10

config:
  hazelcast:
    cluster-name: "hazelcastimdg"
    properties:
      hazelcast.heartbeat.interval.seconds: 10
      hazelcast.jmx: true
      hazelcast.logging.type: log4j2
    network:
      rest-api:
        enabled: true
        endpoint-groups:
          HEALTH_CHECK:
            enabled: true
      join:
        multicast:
          enabled: false
        kubernetes:
          enabled: true
          service-port: 5701
  
