{{- if and .Values.prometheusServer.reachability.service.deploy .Values.prometheusServer.reachability.ingress.deploy -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "prometheus.name" . }}
  labels:
    app.kubernetes.io/name: {{ template "prometheus.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  rules:
    - host: {{ .Values.prometheusServer.reachability.ingress.hostName }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ template "prometheus.name" . }}
                port:
                  name: {{ .Values.prometheusServer.instance.ports.web.name }}
{{- end -}}