apiVersion: v1
kind: Service
metadata:
  name: {{ template "prometheus.name" . }}-service
  labels:
    app.kubernetes.io/name: {{ template "prometheus.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    app.kubernetes.io/name: {{ template "prometheus.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: {{ .Values.prometheusServer.service.type }}
  ports:
    - name: web
      port: {{ .Values.prometheusServer.service.port }}
      targetPort: {{ .Values.prometheusServer.instance.ports.web.name }}