apiVersion: v1
kind: Service
metadata:
  name: {{ template "prometheus.name" . }}
  labels:
    app.kubernetes.io/name: {{ template "prometheus.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    app.kubernetes.io/name: {{ template "prometheus.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: {{ .Values.prometheusServer.reachability.service.type }}
  ports:
    - name: {{ .Values.prometheusServer.instance.ports.web.name }}
      port: {{ .Values.prometheusServer.reachability.service.port }}
      targetPort: {{ .Values.prometheusServer.instance.ports.web.name }}
      {{- if eq .Values.prometheusServer.reachability.service.type "NodePort" }}
      nodePort: {{ .Values.prometheusServer.reachability.service.nodePort }}
      {{- end }}