apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "prometheus.name" . }}-serviceaccount
  labels:
    app.kubernetes.io/name: {{ template "prometheus.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
